service: hackday-customers
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.run
    events:
      - httpApi:
          path: /
          method: get
